kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api", "/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]
build = "pnpm install --frozen-lockfile && pnpm --filter @workspace/api-server run build && PORT=3000 BASE_PATH=/ pnpm --filter @workspace/logistics run build"
run = "node --enable-source-maps artifacts/api-server/dist/index.mjs"

[services.production.env]
NODE_ENV = "production"
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
